#
# Experimental Travis CI.
#
# Linux ARM64 target is pinned on the oldest distribution available on Travis,
# thus matching a generic ARM64 Linux build.

language: shell

git:
  depth: false

jobs:
  include:
    - os: windows

    - os: linux
      dist: xenial
      arch: arm64

    - os: osx
      osx_image: xcode10.1

# Homebrew's libs pollute our build.
install:
  - sudo find /usr/local -type f -name 'libffi*' -exec chmod a+r {} +

before_script:
  - ./brink.sh detect_os

script:
  - ./pythia build && ./pythia test && ./pythia compat
